name: Codex CI

on:
  pull_request:
  push:
    branches: [ work ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Type check
        run: yarn vue-tsc -p tsconfig.json --noEmit
      - name: Build
        run: yarn build
