name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Copy manifest
        run: cp dist/system.json system.json

      - name: Create system.zip
        run: zip -r system.zip . -x '*.git*' -x '.github/*'

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            system.json
            system.zip
